### ISSUE TITLE
Publish to pip

### ISSUE THREAD

**Issue by vvasuki** [karthikraman/panchangam#1]
आमोदो ममामितो दृष्ट्वेमं यत्नम्। निवारयति स्वीयारम्भम् इव https://github.com/sanskrit-coders/jyotisha इत्यत्र। आस्ताम्। अधुना कार्यं किञ्चिद् उपयोक्तृसौकर्याय। pip इत्यत्र प्रकाशनीयम्।  तदन्व् अस्य परीक्षणे वर्धने चान्येषां मादृशानाम् अपि भविष्यति योगदानम्। 

एतदर्थं ननु https://github.com/sanskrit-coders/jyotisha इत्यत्र दृश्यमानम् अस्थिपिञ्जरम् प्रयुज्यताम्। सरलं हि तत्। सर्वमपि module-शः व्यवस्थापनीयम्।

**Comment by vvasuki** [comment]
"You've invited Karthik Raman to Sanskrit Open Source Programmers! They'll be receiving an email shortly. They can also visit https://github.com/sanskrit-coders to accept the invitation." इत्यप्य् आहूतोसि मित्र। (सहकारमसृणतायै निर्मितोऽत्र कश्चित् समूहः। )

यदि च मन्यस उचितम्, पञ्चाङ्गतन्त्रांशं https://github.com/sanskrit-coders/jyotisha इत्यत्र submodule-रूपेण स्थापयितुम् अर्हसि - तस्य कोशस्याधिपत्यन् तर्हि ते दद्याम्। 

सूचनान्तरम् - transliterator-इत्यादिकम् https://github.com/sanskrit-coders/indic_transliteration इत्यनेनापि शक्ये सति न तावदपेक्ष्यते ऽत्र तस्य तन्त्रांशस्य निवेशः।

**Comment by karthikraman** [comment]
submodule-स्थापने  मम  अनुभवं  नास्ति। Fork कृत्वा  भवानेव  कर्तुम्  अर्हति  खलु?

अन्यत्र  कृपया  https://github.com/StotraSamhita/ अपि  पश्यताम्!

**Comment by vvasuki** [comment]
भद्रमुख, सादरं वन्दे। 

- त्वदीयस् तन्त्रांशो https://github.com/sanskrit-coders/jyotisha इत्यत्राङ्गरूपेण संयुक्तः (लघुशोधनैः साकम्)। परीक्षस्व।
- स च तन्त्रांशः pip क्षेत्रे प्रकाशितः - https://pypi.python.org/pypi/jyotisha । 
- उपयोगसूचना जनिताः काश्चन दृश्यन्ते https://sanskrit-coders.github.io/jyotisha/build/html/ इत्यत्र। 
  - असमीचीनरीत्या जनिताः‌ सूचनाः http://jyotisha.readthedocs.io/en/latest/jyotisha_panchangam.html इत्यत्र लभ्याः। भविष्ये कदाचित् शोधनीयं तत्।
- भवान् https://github.com/sanskrit-coders/jyotisha इत्यस्य सर्वाधिकारे स्थापितः। इतः परं तत्रैव परिष्काराधिकं कुर्यादित्यनुरुन्धे। अहमपि यथावकाशं तद्वर्धने यतिष्ये।
  - https://github.com/karthikraman/panchangam इत्यत्र लेखनाधिकारे दत्ते https://github.com/karthikraman/panchangam/tree/master/panchangam इत्यखिलमपीहे निष्कासयितुम् (https://github.com/karthikraman/panchangam/tree/master/panchangam/obsolete इति विहाय )।

गणनाथो जयतुतराम्।

(पश्यताम् ->‌दृश्यताम्)

**Comment by vvasuki** [comment]
> https://github.com/karthikraman/panchangam इत्यत्र लेखनाधिकारे दत्ते https://github.com/karthikraman/panchangam/tree/master/panchangam इत्यखिलमपीहे निष्कासयितुम् (https://github.com/karthikraman/panchangam/tree/master/panchangam/obsolete इति विहाय )।

एतदधुना साधितम् भवदनुज्ञया। पिदधामि सूत्रम्।
