### ISSUE TITLE
Question: Can this be used to calculate tithi form date?

### ISSUE THREAD

**Issue by praveens96** [karthikraman/panchangam#11]
I tried looking at the docs but couldn't find.
I want to calculate tithi etc from calendar date. is it possible using this repo?

**Comment by vvasuki** [comment]
Try https://jyotisham.github.io/jyotisha/software/for_users/

**Comment by praveens96** [comment]
thanks for the prompt response, looking at it i think need to use get_tithi function.
is it possible to find occurrence of same tithi in a given year? can you please suggest?

**Comment by vvasuki** [comment]
> thanks for the prompt response, looking at it i think need to use get_tithi function. is it possible to find occurrence of same tithi in a given year? can you please suggest?

A few lines of python code should get you that. If you do write such a function, you're welcome to contribute it via a pull request to https://github.com/jyotisham/jyotisha/blob/master/jyotisha/panchaanga/spatio_temporal/annual.py .
