### ISSUE TITLE
How to create pdf with tamil font

### ISSUE THREAD

**Issue by maduraisuresh** [karthikraman/panchangam#4]
How to create pdf with tamil font

**Comment by karthikraman** [comment]
Currently not supported. Although you can access an ics calendar here: https://calendar.google.com/calendar/b/2?cid=bmFpdTBnYmJzaWtvNHY0ZGs0b2phbGRnYWtAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ
